name: test matrix

on:
  workflow_dispatch:
    inputs:
      names:
        description: comma separated names
        required: true
        default: one,two,three

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - id: names
        run: |
          NAMES=$(echo "${{ github.event.inputs.names }}" | \
            awk '{
              split($0, array, ",");
              printf("[\"%s", array[1]);
              for (i=2; i <= length(array); i++) {
                printf(", \"%s\"", array[i])
              };
              print("]")
            }')
          echo "::set-output name=list::$(echo $NAMES)"

    outputs:
      names: ${{ steps.names.outputs.list }}

  test:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - run: echo ${{ steps.matrix.outputs.names }}
