name: test matrix

on:
  workflow_dispatch:
    inputs:
      names:
        description: comma separated names
        required: true
        default: one,two,three

jobs:
  names:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          NAMES=$(echo "${{ github.event.inputs.names }}" | \
            awk '{
              split($0, array, ",");
              printf("[\"%s", array[1]);
              for (i=2; i <= length(array); i++) {
                printf(", \"%s\"", array[i])
              };
              print("]")
            }')
          echo NAMES=$NAMES >> $GITHUB_ENV

    outputs:
      names: ${{ env.NAMES }}

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ steps.matrix.outputs.names }}
