name: test matrix

on:
  workflow_dispatch:
    inputs:
      names:
        description: comma separated names
        required: true
        default: one,two,three

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - id: names
        run: |
          echo "::set-output name=list::$(echo "${{ github.event.inputs.names }}" | \
            awk '{
              split($0, array, ",");
              printf("[\\\"%s", array[1]);
              for (i=2; i <= length(array); i++) {
                printf(", \\\"%s\\\"", array[i])
              };
              print("]")
            }')"

      - run: echo "${{ steps.names.outputs.list }}"

    outputs:
      names: ${{ steps.names.outputs.list }}

  test:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        name: ${{ fromJson(needs.matrix.outputs.names) }}

    steps:
      - run: echo ${{ matrix.name }}
