name: testing PR's merging behaviour (13th step)

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  packer:
    if: github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.head.ref, 'pr/prefixed/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git --no-pager log -n 1 --decorate

      - run: |
          echo "${{ github.event.pull_request.head.ref }}"
