name: testing run step env vars behaviour

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FIRST: one

    steps:
      - run:
          declare -xp
        env:
          SECOND: two
